apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp.xk8s.platformref.upbound.io
  labels:
    cloud: gcp
spec:
  compositeTypeRef:
    apiVersion: platformref.upbound.io/v1alpha1
    kind: XK8s
  resources:
    - base:
        apiVersion: container.gcp.upbound.io/v1beta1
        kind: Cluster
        metadata:
          annotations: #patched
        spec:
          writeConnectionSecretToRef:
            namespace: #patched
            name: #patched
          forProvider:
            initialNodeCount: 1
            removeDefaultNodePool: true
            location: us-west2 # USER_INPUT?
            masterAuth:
              # setting this master auth user name enables basic auth so that a client (e.g.,
              # provider-helm), can connect with the generated kubeconfig from the connection secret
              - username: admin
                clientCertificateConfig:
                  - issueClientCertificate: true
            masterAuthorizedNetworksConfig:
              - enabled: false
            ipAllocationPolicy:
              - useIpAliases: true
                clusterSecondaryRangeName: pods
                servicesSecondaryRangename: services
            loggingService: logging.googleapis.com/kubernetes
            monitoringService: monitoring.googleapis.com/kubernetes
            #addonsConfig:
            #  - gcePersistentDiskCsiDriverConfig:
            #    enabled: true
      name: kubernetesCluster
      patches:
        - fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - fromFieldPath: spec.id
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-gkecluster"
        - fromFieldPath: spec.claim.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        # Create this cluster in the Network and Subnetwork referenced by network ID
        - fromFieldPath: "spec.id"
          toFieldPath: spec.forProvider.networkSelector.matchLabels[networks.gcp.platformref.crossplane.io/network-id]
        - fromFieldPath: "spec.id"
          toFieldPath: spec.forProvider.subnetworkSelector.matchLabels[networks.gcp.platformref.crossplane.io/network-id]
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
    # Each cluster has one node pool. Its nodes are spread evenly across the zones
    # in which the cluster exists.
    - base:
        apiVersion: container.gcp.upbound.io/v1beta1
        kind: NodePool
        spec:
          forProvider:
            location: us-west2
            initialNodeCount: 1
            clusterSelector:
              # Attach this node pool to the GKECluster created above.
              matchControllerRef: true
            #autoscaling:
            #  - enabled: true
            nodeConfig:
              - diskType: pd-standard
                diskSizeGb: 100
                oauthScopes:
                  - https://www.googleapis.com/auth/cloud-platform
            management:
              - autoRepair: true
                autoUpgrade: true
      name: kubernetesNodePool
      patches:
        - fromFieldPath: metadata.annotations[crossplane.io/external-name]
        - fromFieldPath: spec.parameters.nodes.size
          toFieldPath: spec.forProvider.nodeConfig[0].machineType
          transforms:
            - type: map
              map:
                small: n1-standard-4
                medium: n1-standard-16
                large: n1-standard-32
        - fromFieldPath: spec.parameters.nodes.count
          toFieldPath: spec.forProvider.initialNodeCount
        - fromFieldPath: spec.parameters.nodes.count
          toFieldPath: spec.forProvider.autoscaling[0].minNodeCount
        - fromFieldPath: spec.parameters.nodes.count
          toFieldPath: spec.forProvider.autoscaling[0].maxNodeCount
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              key: kubeconfig
      name: helm-providerConfig
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.credentials.secretRef.namespace
        - fromFieldPath: "metadata.uid"
          toFieldPath: spec.credentials.secretRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-gkecluster"
      readinessChecks:
        - type: None